version: 2.1

orbs:
  node: circleci/node@5

jobs:
  install_deps:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm

  build:
    executor: node/default
    steps:
      - checkout
      - run: echo "Building project..."
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Clean & Package
          command: npm run build

  unit-tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Jest tests
          command: npm test --ci
      - store_test_results:
          path: ./test-results/

  integration-tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running integration tests..."
      - run: npm run test:integration

  regression-tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running regression tests..."
      - run: npm run test:regression

  security-tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running security tests..."
      - run: npm run test:security

  deploy_dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to development environment..."

  deploy_integration:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to integration environment..."

  deploy_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "Deploying to production environment..."

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - install_deps

      - build:
          requires:
            - install_deps

      - unit-tests:
          requires:
            - build

      - integration-tests:
          requires:
            - build

      - regression-tests:
          requires:
            - build

      - security-tests:
          requires:
            - build

      - deploy_dev:
          requires:
            - unit-tests
            - integration-tests
            - regression-tests
          filters:
            branches:
              only: develop

      - deploy_integration:
          requires:
            - unit-tests
            - integration-tests
            - regression-tests
          filters:
            branches:
              only: integration

      - deploy_prod:
          requires:
            - unit-tests
            - integration-tests
            - regression-tests
            - security-tests
          filters:
            branches:
              only: main
